Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WatchParty.Data;
using WatchParty.Data.Enteties;
using WatchParty.DTOs;
using WatchParty.Services;
using WatchParty.Services.Abstractions;

namespace WatchParty.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorServices _actorService;
        private readonly IMovieServices _movieService;

        public ActorsController(IActorServices actorService, IMovieServices movieServices)
        {
            _actorService = actorService;
            _movieService = movieServices;
        }
        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _actorService.GetAllAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _actorService.GetByIdAsync(id.Value);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        [Authorize(Roles = "Admin")]
        // GET: Actors/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Movies = await _movieService.GetAllAsync();
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Actors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ActorCreateEditDTO actorDto)
        {
            if (ModelState.IsValid)
            {
                await _actorService.CreateAsync(actorDto);
                return RedirectToAction(nameof(Index));
            }
            return View(actorDto);
        }

        [Authorize(Roles = "Admin")]
        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _actorService.GetByIdEditAsync(id.Value);
            if (actor == null)
            {
                return NotFound();
            }
            ViewBag.Movies = await _movieService.GetAllAsync();
            ViewBag.SelectedMovies = actor.Movies.Select(movie => movie.ID).ToList();

            return View(new ActorCreateEditDTO()
            {
                ID = actor.ID,
                FirstName = actor.FirstName,
                LastName = actor.LastName,
                Age = actor.Age,
                ImageUrl = actor.ImageUrl,
                MoviesIds = actor.MoviesIds
            });
        }

        [Authorize(Roles = "Admin")]
        // POST: Actors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ActorCreateEditDTO actorDto)
        {
            if (id != actorDto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _actorService.UpdateAsync(actorDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ActorExistsAsync(actorDto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actorDto);
        }

        [Authorize(Roles = "Admin")]
        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _actorService.GetByIdAsync(id.Value);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }


        [Authorize(Roles = "Admin")]
        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _actorService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ActorExistsAsync(int id)
        {
            return (await _actorService.GetByIdAsync(id)) != null;
        }
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WatchParty.Data;
using WatchParty.Data.Enteties;
using WatchParty.DTOs;
using WatchParty.Services.Abstractions;

namespace WatchParty.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryServices _categoryService;

        public CategoriesController(ICategoryServices categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoryService.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [Authorize(Roles = "Admin")]
        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryDTO categoryDto)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.CreateAsync(categoryDto);
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDto);
        }

        [Authorize(Roles = "Admin")]
        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoryService.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CategoryDTO categoryDto)
        {
            if (id != categoryDto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _categoryService.UpdateAsync(categoryDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await CategoryExistsAsync(categoryDto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDto);
        }


        [Authorize(Roles = "Admin")]
        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoryService.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [Authorize(Roles = "Admin")]
        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _categoryService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> CategoryExistsAsync(int id)
        {
            return (await _categoryService.GetByIdAsync(id)) != null;
        }
    }
}

Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WatchParty.Data;
using WatchParty.Data.Enteties;
using WatchParty.DTOs;
using WatchParty.Services.Abstractions;

namespace WatchParty.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieServices _movieService;
        private readonly IActorServices _actorService;
        private readonly ICategoryServices _categoryServices;


        public MoviesController(IMovieServices movieService, IActorServices actorService, ICategoryServices categoryServices)
        {
            _movieService = movieService;
            _actorService = actorService;
            _categoryServices = categoryServices;   
        }


        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _movieService.GetAllAsync());
        }

        [Route("Movies/Category/{name}")]
        public async Task<IActionResult> Category(string name)
        {
            return View(_movieService.GetByCategory(name));
        }

        [Authorize]
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieService.GetByIdAsync(id.Value);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [Authorize(Roles = "Admin")]
        // GET: Movies/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Actors = await _actorService.GetAllAsync();
            
            ViewBag.Categories = await _categoryServices.GetAllAsync();
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Movies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieCreateEditDTO movieDto)
        {
            if (ModelState.IsValid)
            {
                await _movieService.CreateAsync(movieDto);
                return RedirectToAction(nameof(Index));
            }
            return View(movieDto);
        }

        [Authorize(Roles = "Admin")]
        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieService.GetByIdEditAsync(id.Value);
            if (movie == null)
            {
                return NotFound();
            }
            ViewBag.Actors = await _actorService.GetAllAsync();
            ViewBag.SelectedActors = movie.Actors.Select(actor => actor.ID).ToList(); 
            ViewBag.Categories = await _categoryServices.GetAllAsync();
            ViewBag.SelectedCategories = movie.Categories.Select(cat => cat.ID).ToList(); 

            return View(new MovieCreateEditDTO()
            {
                ID = movie.ID,
                Name = movie.Name,
                Description = movie.Description,
                ImageUrl = movie.ImageUrl,
                VideoPath = movie.VideoPath,
                ActorIds = movie.ActorIds,
                CategoryIds = movie.CategoryIds

            });
        }

        [Authorize(Roles = "Admin")]
        // POST: Movies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MovieCreateEditDTO movieDto)
        {
            if (id != movieDto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _movieService.UpdateAsync(movieDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await MovieExistsAsync(movieDto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movieDto);
        }

        [Authorize(Roles = "Admin")]
        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieService.GetByIdAsync(id.Value);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [Authorize(Roles = "Admin")]
        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _movieService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MovieExistsAsync(int id)
        {
            return (await _movieService.GetByIdAsync(id)) != null;
        }
    }
}

Views/Movies/Category.cshtml
@model IEnumerable<WatchParty.DTOs.MovieDTO>

@{
    ViewData["Title"] = "Category";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2></h2>

    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Categories</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID">
                            <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" class="img-thumbnail" width="80" />
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.CategoryNames)</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Movies/Create.cshtml
@model WatchParty.DTOs.MovieCreateEditDTO

@{
    ViewData["Title"] = "Create";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2>Create Movie</h2>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input asp-for="ImageUrl" class="form-control" />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="VideoPath" class="control-label"></label>
                    <input asp-for="VideoPath" class="form-control" />
                    <span asp-validation-for="VideoPath" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryIds" class="control-label"></label>
                    <select multiple="multiple" asp-for="CategoryIds" class="form-control" asp-items="@(new MultiSelectList(ViewBag.Categories, "ID", "Name"))"></select>
                </div>
                <div class="form-group">
                    <label asp-for="ActorIds" class="control-label"></label>
                    <select multiple="multiple" asp-for="ActorIds" class="form-control" asp-items="@(new MultiSelectList(ViewBag.Actors, "ID", "FullName"))"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Movies/Delete.cshtml
@model WatchParty.DTOs.MovieDTO

@{
    ViewData["Title"] = "Delete";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2>Delete Movie</h2>
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <dl class="row">
                <dt class="col-sm-4">Image</dt>
                <dd class="col-sm-8">
                    <img src="@Html.DisplayFor(model => model.ImageUrl)" class="img-thumbnail" width="200" />
                </dd>
                <dt class="col-sm-4">Name</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Name)</dd>
                <dt class="col-sm-4">Description</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Description)</dd>
            </dl>
            <form asp-action="Delete">
                <input type="hidden" asp-for="ID" />
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </form>
        </div>
    </div>
</div>

Views/Movies/Details.cshtml
@model WatchParty.DTOs.MovieDTO

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2>Movie Details</h2>
    <hr />
    <div class="">
        <div class="col-md-8">
            <dl class="row">
                <dt class="col-sm-3">Image:</dt>
                <dd class="col-sm-9">
                    <img src="@Html.DisplayFor(model => model.ImageUrl)" class="img-thumbnail" width="280" />
                </dd>
                <dt class="col-sm-3">Name: </dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>
                <dt class="col-sm-3">Description: </dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Description)</dd>
            </dl>
            <div class="video-frame">
                <video controls>
                    <source src="@Url.Content($"~/videos/{Model.VideoPath}.mp4")" type="video/mp4" />
                </video>
            </div>
            <div class="p-3">
                <h5>Categories:</h5>
                @if (Model.Categories.Count <= 0)
                {
                    <div>There are no categories for this movie yet.</div>
                }
                else
                {
                    <div class="p-1">
                        @foreach (var item in Model.Categories)
                            {
                            <a asp-controller="Movies" asp-action="Category" asp-route-id="@item.Name"><span class="category">@item.Name </span></a>
                            }
                    </div> 
            }

            </div>
            <div class="p-3">
                <h5>Starring:</h5>
                @if (Model.Actors.Count <= 0)
                {
                    <div>There are no actors for this movie yet.</div>
                }
                else
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Actors)
                            {
                                <tr>
                                    <td>
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@item.ID">
                                            <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" class="img-thumbnail" width="100" />
                                        </a>
                                    </td>
                                    <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.ID" class="btn btn-primary">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model?.ID" class="btn btn-danger">Delete</a>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

Views/Movies/Edit.cshtml
@model WatchParty.DTOs.MovieCreateEditDTO

@{
    ViewData["Title"] = "Edit";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2>Edit Movie</h2>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input asp-for="ImageUrl" class="form-control" />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="VideoPath" class="control-label"></label>
                    <input asp-for="VideoPath" class="form-control" />
                    <span asp-validation-for="VideoPath" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryIds" class="control-label"></label>
                    <select multiple="multiple" asp-for="CategoryIds" class="form-control" asp-items="@(new MultiSelectList(ViewBag.Categories, "ID", "Name", ViewBag.SelectedCategories))"></select>
                </div>
                <div class="form-group">
                    <label asp-for="ActorIds" class="control-label"></label>
                    <select multiple="multiple" asp-for="ActorIds" class="form-control" asp-items="@(new MultiSelectList(ViewBag.Actors, "ID", "FullName", ViewBag.SelectedActors))"></select>
                </div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Movies/Index.cshtml
@model IEnumerable<WatchParty.DTOs.MovieDTO>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="~/css/websiteStyle.css" asp-append-version="true" />

<div class="container">
    <h2>All Movies</h2>
    <p>
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Categories</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID">
                            <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" class="img-thumbnail" width="80" />
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.CategoryNames)</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>